name: esgi_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  # State management / Dependancies injection / Work without context
  get: ^3.1.0

  # Firebase
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  

  # Image
  image_picker: ^0.6.7+2             # recup image gallery / camera
  cached_network_image: ^2.2.0       # gestion cache image
  flutter_swiper: ^1.1.6             # Swipe image
  path_provider: ^1.6.8

  # Utils
  #auto_size_text: ^2.1.0             # resize auto text
  #connectivity: ^0.4.8+2             # gestion connection inter(net
  jiffy: ^3.0.1                       # gestion date
  font_awesome_flutter: ^8.8.1
  curved_navigation_bar: ^0.3.2
  the_validator: ^1.0.1               # validator textfield

  # Location
  location: ^3.0.2
  geocoder: ^0.2.1
  flutter_map: ^0.9.0

  lottie: ^0.4.1


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  flutter_rename_app: ^1.0.0


flutter_rename_app:
  application_name: Wemouv
  dart_package_name: esgi_project
  application_id: fr.esgi.wemouvflutter
  bundle_id: fr.esgi.wemouvflutter
  android_package_name: fr.esgi.wemouvflutter

  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon.png"



# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
     - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

